language: node_js

node_js:
  - stable

dist: trusty

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn test:coverage

script:
  - yarn build
